# ==============================================================================
# PROMPT TEMPLATES LIBRARY
# ==============================================================================

STYLE_OPENERS = {
    "formal": [
        "Please produce a fully traceable {key} configuration. Use the identifier prefix {uniq_prefix} for every artifact.",
        "Kindly supply a standards-compliant {key} architecture with deterministic timing; all names must begin with {uniq_prefix}.",
        "Submit a rigorously structured {key} AUTOSAR AE XML that references {uniq_prefix} across ECUs, chiplets, and analyses.",
        "Provide a certification-ready {key} definition referencing {uniq_prefix} across events, ports, and chiplets.",
        "Deliver an evidence-backed {key} plan with {uniq_prefix} names spanning ECUs, networks, and CPU clusters.",
        "Assemble a validation-ready {key} package that cross-references lifecycle artifacts through {uniq_prefix}.",
        "Draft an audit-focused {key} dossier tying diagnostics, timing, and chiplets together via {uniq_prefix}.",
        "Compose a regulatory review packet for {key} where every structural element is tagged under {uniq_prefix}.",
    ],
    "user_friendly": [
        "I need a {key} setup that is efficient and safe. Please keep names unique (use {uniq_prefix} as a prefix).",
        "Help me craft a trustworthy {key} configuration for a mixed-criticality vehicle; tag everything with {uniq_prefix}.",
        "Let's build a clear, maintainable {key} design. Reuse the prefix {uniq_prefix} so I can trace components quickly.",
        "Walk me through a {key} arrangement that's easy to maintain; keep using {uniq_prefix} to avoid confusion.",
        "I'm aiming for a safe {key} blueprint; please label everything with {uniq_prefix} so audits stay simple.",
        "Outline an intuitive {key} concept and keep every identifier tied to {uniq_prefix} so newcomers stay oriented.",
        "Make a reassuring {key} reference that narrates ports, timing, and safety by leaning on the {uniq_prefix} prefix.",
        "Share a coach-style walkthrough of {key} decisions, anchoring each object with the {uniq_prefix} identifier.",
    ],
    "concise": [
        "Provide a lean, safety-compliant {key} configuration. Keep instructions crisp and reuse the prefix {uniq_prefix} for every identifier.",
        "Deliver a minimal-yet-complete {key} XML snapshot; each element must carry the {uniq_prefix} prefix.",
        "Summarize the {key} stack with only essential structure and {uniq_prefix} labels.",
        "Outline the {key} package in tight prose, tagging each artifact with {uniq_prefix}.",
        "Need a terse {key} manifest—facts only, with identifiers prefixed by {uniq_prefix}.",
        "Compress the {key} evidence trail into a checklist that leans on {uniq_prefix} naming throughout.",
        "Issue a briefing-style {key} outline where every dependency is labeled via {uniq_prefix}.",
        "Publish a quick-reference {key} digest and bind the hierarchy with the {uniq_prefix} prefix.",
    ],
    "conversational": [
        "Could you sketch a realistic {key} topology for me? Stick with the {uniq_prefix} prefix so we stay organized.",
        "I'm iterating on a {key} concept—can you lay out an AUTOSAR AE example using {uniq_prefix} names throughout?",
        "Mind drafting a {key} blueprint that highlights timing, power, and chiplet ties, all tagged with {uniq_prefix}?",
        "As we iterate on this {key} rollout, please keep every identifier rooted in {uniq_prefix}.",
        "Let's co-design a {key} mockup where timing, power, and chiplets all reuse the {uniq_prefix} tag.",
        "Talk me through a {key} prototype where {uniq_prefix} keeps diagnostics, ports, and tests aligned.",
        "Frame a collaborative {key} plan that balances safety and compute loads while repeating {uniq_prefix}.",
        "Walk me through lessons learned from a {key} deployment and weave {uniq_prefix} into every reference.",
    ],
    "professional": [
        "Generate an AUTOSAR AE XML for {key} with precise, verifiable requirements. Use unique IDs with prefix {uniq_prefix}.",
        "Compose a deployment-ready {key} model emphasizing compliance, diagnostics, and {uniq_prefix} identifiers.",
        "Produce a technical {key} specification that balances performance and safety, referencing {uniq_prefix} everywhere.",
        "Deliver an engineering-grade {key} dossier with traceable IDs using the {uniq_prefix} prefix.",
        "Assemble a review-ready {key} reference model with lifecycle controls keyed by {uniq_prefix}.",
        "Publish a contract-grade {key} solution that captures scheduling and power metrics under {uniq_prefix}.",
        "Curate a portfolio of {key} architectural views, cross-linked through the {uniq_prefix} naming convention.",
        "Deliver a supplier-facing {key} statement of work with every asset organized under {uniq_prefix}.",
    ],
}

SCENARIO_LINE_TEMPLATES = {
    "formal": [
        "Scenario {scenario}: deliver a standards-driven {key} package with {uniq_prefix} prefixes.",
        "Operating conditions {scenario}; compile a compliance-ready {key} configuration anchored by {uniq_prefix}.",
        "Given {scenario}, prepare exhaustive {key} artifacts stamped with {uniq_prefix}.",
        "Context {scenario}: produce evidence-backed {key} definitions referencing {uniq_prefix}.",
        "Mission {scenario}: align risk controls, timing budgets, and {key} assets through {uniq_prefix}.",
        "Regulatory context {scenario}: demonstrate every {key} decision with identifiers rooted in {uniq_prefix}.",
        "Lifecycle scenario {scenario}: orchestrate diagnostics and upgrades using the {uniq_prefix} namespace.",
        "Sign-off gate {scenario}: show a validated {key} slice labeled via {uniq_prefix}.",
    ],
    "user_friendly": [
        "User journey {scenario}: keep the {key} setup approachable and tag everything with {uniq_prefix}.",
        "Working within {scenario}, make the {key} blueprint simple while reusing {uniq_prefix} across artifacts.",
        "Friendly request for {scenario}: arrange the {key} elements so each identifier starts with {uniq_prefix}.",
        "Help me address {scenario} by shaping a reassuring {key} design labeled with {uniq_prefix}.",
        "Experience map {scenario}: narrate the {key} rationale while leaning on {uniq_prefix}.",
        "Support moment {scenario}: highlight safety and observability with the {uniq_prefix} prefix.",
        "Iteration loop {scenario}: keep stakeholders aligned by repeating {uniq_prefix} markers.",
        "Adoption phase {scenario}: maintain clarity by binding the {key} stack to {uniq_prefix}.",
    ],
    "concise": [
        "Scope {scenario}: provide only the essential {key} details and prefix them with {uniq_prefix}.",
        "{scenario} focus: supply the critical {key} artifacts, each beginning with {uniq_prefix}.",
        "Brief for {scenario}: keep the {key} surfaces lean and labeled {uniq_prefix}.",
        "{scenario} requirement: minimal {key} structures, uniformly tagged with {uniq_prefix}.",
        "Checkpoint {scenario}: present the {key} delta using {uniq_prefix} handles.",
        "Sprint goal {scenario}: distill the {key} increments and assign {uniq_prefix} names.",
        "Status ping {scenario}: ensure every referenced module is covered by {uniq_prefix}.",
        "Escalation {scenario}: surface the top {key} risks using {uniq_prefix} identifiers.",
    ],
    "conversational": [
        "For {scenario}, let's sketch the {key} plan and reuse {uniq_prefix} so we stay aligned.",
        "Thinking about {scenario}; can we map the {key} flow with every item starting {uniq_prefix}?",
        "Given {scenario}, let's piece together the {key} stack and keep {uniq_prefix} on each artifact.",
        "While we cover {scenario}, please outline the {key} structure and stick with {uniq_prefix} as the prefix.",
        "As {scenario} evolves, let's call out each {key} tweak using the {uniq_prefix} tag.",
        "Since {scenario} stresses timing, let's anchor buffers and runnables with {uniq_prefix}.",
        "When {scenario} hits debugging mode, I want {uniq_prefix} to guide us through the XML.",
        "While calibrating {scenario}, keep procurement-ready naming via {uniq_prefix}.",
    ],
    "professional": [
        "Professional brief {scenario}: craft a production-grade {key} solution using the {uniq_prefix} prefix.",
        "Execution context {scenario}; assemble an audit-ready {key} package anchored by {uniq_prefix}.",
        "For {scenario}, deliver a reference-quality {key} configuration with names starting {uniq_prefix}.",
        "Project scenario {scenario}: supply a review-ready {key} dossier, every element tagged {uniq_prefix}.",
        "Operational backdrop {scenario}: align KPIs, safety, and {key} assets with {uniq_prefix}.",
        "Program milestone {scenario}: document each {key} stream through {uniq_prefix} traceability.",
        "Contract clause {scenario}: ensure acceptance criteria reference the {uniq_prefix} namespace.",
        "Risk control {scenario}: coordinate mitigation artifacts using {uniq_prefix} identifiers.",
    ],
    "default": [
        "Scenario: {scenario}",
        "Operating context: {scenario}",
        "Primary scenario {scenario}; maintain {uniq_prefix} identifiers for {key}.",
        "Use {scenario} as context and ensure {key} elements rely on {uniq_prefix} prefixes.",
        "Context {scenario}: present {key} design notes under {uniq_prefix}.",
        "Backdrop {scenario}: weave requirements and metrics via {uniq_prefix}.",
        "Situation {scenario}: summarize ports, runnables, and mappings tagged {uniq_prefix}.",
        "Briefing {scenario}: reiterate every artifact inside the {uniq_prefix} namespace.",
    ],
}

SCENARIO_CYCLE = [
    "Urban braking with high pedestrian density; critical loops <50us.",
    "Highway cruise with lane-keeping; energy budget <100 mW per HWIP.",
    "Battery-saving mode for infotainment; idle leakage <0.5 mW.",
    "Mixed-criticality ADAS (ASIL-D) with logs every 100–250 ms.",
]

# Detailed prompt templates with variations for each category
PROMPT_TEMPLATES = {
    "generate_time_latency": [
        "Generate a single XML element for {key}.\nRequirements:\n1. Use the correct schema attributes (value, unit).\n2. Ensure the unit is valid (s, ms, us, ns).\n3. Value should be a reasonable positive number.\n4. Do not wrap in a root element, just the single element.\n",
        "Create a valid AUTOSAR AE XML snippets for {key}.\nFocus on:\n- High precision values\n- Correct unit specification\n- Adherence to XSD simple types\n",
        "Produces a {key} element for a high-performance simulation.\nContext:\n- Real-time constraints\n- Latency critical path\n- Use 'us' or 'ns' for units\n",
        "Generate an XML configuration for {key} representing a long-duration event.\nContext:\n- System timeout or watchdog period\n- Use 'ms' or 's' for units\n",
        "Write a schema-compliant {key} tag.\nAttributes:\n- value: integer or float as required\n- unit: standard time unit\n",
    ],
    "generate_core": [
        "I need you to design a comprehensive automotive system architecture focusing on {key}. The system should include:\n\n1. Multiple ECUs with different configurations and capabilities\n2. SoC implementations with varying performance characteristics\n3. Complete hardware abstraction layers\n4. Proper inter-ECU communication protocols\n5. Real-time processing capabilities\n6. Power management and thermal considerations\n7. Safety-critical system components\n8. Scalable architecture for future enhancements\n\nPlease generate a complete AUTOSAR AE XML configuration that demonstrates best practices for automotive system design, including proper component relationships, data flow, and system integration patterns.",
        "Design an advanced automotive control system with focus on {key} components. Requirements:\n\n- Implement a distributed architecture with multiple processing units\n- Include both high-performance and low-power processing elements\n- Ensure proper data synchronization between components\n- Implement fault-tolerant communication mechanisms\n- Include comprehensive power management strategies\n- Design for automotive safety standards compliance\n- Support for both real-time and non-real-time applications\n- Scalable design for different vehicle configurations\n\nGenerate a detailed AUTOSAR AE XML that showcases professional automotive system design principles.",
        "Create a sophisticated automotive system configuration emphasizing {key} elements. The system must:\n\n1. Support multiple vehicle domains (powertrain, chassis, body, infotainment)\n2. Implement hierarchical processing architecture\n3. Include advanced communication protocols (CAN, Ethernet, LIN)\n4. Provide comprehensive diagnostic capabilities\n5. Support over-the-air updates\n6. Implement security measures for connected vehicles\n7. Include predictive maintenance capabilities\n8. Support autonomous driving functions\n\nPlease provide a complete AUTOSAR AE XML configuration that demonstrates enterprise-level automotive system design.",
        "Develop a next-generation automotive system architecture with emphasis on {key}. Key requirements:\n\n- Heterogeneous computing platforms with mixed criticality support\n- Advanced sensor fusion and data processing capabilities\n- Machine learning integration for intelligent decision making\n- Edge computing support for real-time processing\n- Cybersecurity measures for connected vehicle protection\n- Adaptive system behavior based on driving conditions\n- Support for V2X (Vehicle-to-Everything) communication\n- Compliance with ISO 26262 functional safety standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge automotive system design.",
        "Design a modular automotive system focusing on {key} components. The architecture should:\n\n- Support plug-and-play component integration\n- Enable dynamic system reconfiguration\n- Provide comprehensive system monitoring and diagnostics\n- Include advanced thermal management strategies\n- Support both centralized and distributed processing\n- Implement intelligent resource allocation\n- Provide seamless integration with cloud services\n- Support continuous system optimization\n\nPlease create a detailed AUTOSAR AE XML configuration that showcases modern automotive system architecture.",
    ],
    "generate_interface": [
        "Design a comprehensive interface architecture for automotive systems focusing on {key}. Requirements:\n\n1. Multiple interface types with different data characteristics\n2. Proper data validation and error handling mechanisms\n3. Support for both synchronous and asynchronous communication\n4. Interface versioning and backward compatibility\n5. Performance optimization for different data types\n6. Security measures for sensitive data transmission\n7. Diagnostic capabilities for interface monitoring\n8. Support for both local and remote interfaces\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional interface design patterns.",
        "Create an advanced interface system for automotive applications with emphasis on {key}. The design should include:\n\n- Multiple data exchange patterns (publish-subscribe, request-response, streaming)\n- Support for different data formats (structured, binary, text)\n- Interface abstraction layers for different communication protocols\n- Comprehensive error detection and recovery mechanisms\n- Performance monitoring and optimization features\n- Security protocols for data integrity and confidentiality\n- Interface testing and validation frameworks\n- Support for dynamic interface configuration\n\nPlease provide a complete AUTOSAR AE XML that showcases modern automotive interface design.",
        "Develop a sophisticated interface architecture for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for heterogeneous computing environments\n2. Multi-domain interface integration (ADAS, infotainment, powertrain)\n3. Real-time interface performance guarantees\n4. Advanced data compression and optimization techniques\n5. Interface redundancy and failover mechanisms\n6. Support for edge computing and cloud integration\n7. Machine learning interface optimization\n8. Compliance with automotive cybersecurity standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge interface design principles.",
        "Design an intelligent interface system for autonomous vehicles with focus on {key}. The system must:\n\n- Support high-bandwidth sensor data processing\n- Enable real-time decision making interfaces\n- Provide secure communication channels\n- Support adaptive interface behavior\n- Include advanced data fusion capabilities\n- Implement intelligent interface routing\n- Support both deterministic and probabilistic interfaces\n- Enable seamless integration with AI/ML components\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation interface design.",
        "Create a scalable interface architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for multiple communication protocols (CAN, Ethernet, 5G, WiFi)\n- Advanced interface security and encryption\n- Support for over-the-air interface updates\n- Intelligent interface load balancing\n- Support for both local and cloud-based interfaces\n- Advanced interface analytics and monitoring\n- Support for interface virtualization\n- Compliance with automotive communication standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle interface design.",
    ],
    "generate_swc": [
        "Design a comprehensive software component architecture focusing on {key}. Requirements:\n\n1. Multiple SWC types with different functional characteristics\n2. Proper component interfaces and dependencies\n3. Support for both periodic and event-driven execution\n4. Component lifecycle management and state handling\n5. Error handling and recovery mechanisms\n6. Performance optimization and resource management\n7. Component testing and validation frameworks\n8. Support for component reuse and modularity\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional software component design.",
        "Create an advanced software component system for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical component architecture with clear separation of concerns\n- Support for both synchronous and asynchronous component communication\n- Component versioning and compatibility management\n- Advanced scheduling and priority management\n- Component security and access control mechanisms\n- Support for component hot-swapping and dynamic loading\n- Comprehensive component monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for component verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern software component architecture.",
        "Develop a sophisticated software component ecosystem for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for heterogeneous computing platforms\n2. Multi-domain component integration (safety, security, performance)\n3. Advanced component orchestration and workflow management\n4. Support for AI/ML component integration\n5. Component-based system evolution and updates\n6. Advanced component testing and simulation capabilities\n7. Support for distributed component execution\n8. Compliance with automotive software standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge software component design.",
        "Design an intelligent software component system for autonomous driving with focus on {key}. The system must:\n\n- Support real-time sensor data processing components\n- Enable AI/ML component integration\n- Provide advanced component coordination mechanisms\n- Support adaptive component behavior\n- Include comprehensive component safety mechanisms\n- Implement intelligent component resource management\n- Support both deterministic and probabilistic components\n- Enable seamless component evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation software component design.",
        "Create a modular software component architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-native component design\n- Advanced component security and isolation\n- Support for component microservices architecture\n- Intelligent component load balancing\n- Support for both local and distributed components\n- Advanced component analytics and monitoring\n- Support for component containerization\n- Compliance with automotive software standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle software component design.",
    ],
    "generate_behavior": [
        "Design a comprehensive internal behavior system focusing on {key}. Requirements:\n\n1. Multiple behavior patterns with different execution characteristics\n2. Proper state management and transition handling\n3. Support for both deterministic and non-deterministic behaviors\n4. Advanced timing and synchronization mechanisms\n5. Behavior composition and modularity\n6. Error handling and exception management\n7. Performance monitoring and optimization\n8. Support for behavior testing and validation\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional behavior design patterns.",
        "Create an advanced internal behavior architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical behavior composition with clear abstraction levels\n- Support for both reactive and proactive behavior patterns\n- Advanced event handling and message processing\n- Behavior scheduling and resource allocation mechanisms\n- Support for behavior adaptation and learning\n- Comprehensive behavior monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for behavior verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern behavior design principles.",
        "Develop a sophisticated behavior system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for adaptive and intelligent behavior patterns\n2. Multi-modal behavior integration (sensor fusion, decision making)\n3. Advanced behavior orchestration and coordination\n4. Support for distributed behavior execution\n5. Behavior-based system optimization and learning\n6. Advanced behavior testing and simulation capabilities\n7. Support for behavior evolution and updates\n8. Compliance with automotive behavior standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge behavior design.",
        "Design an intelligent behavior system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time decision making behaviors\n- Enable AI/ML behavior integration\n- Provide advanced behavior coordination mechanisms\n- Support adaptive behavior patterns\n- Include comprehensive behavior safety mechanisms\n- Implement intelligent behavior resource management\n- Support both deterministic and probabilistic behaviors\n- Enable seamless behavior evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation behavior design.",
        "Create a modular behavior architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based behavior processing\n- Advanced behavior security and isolation\n- Support for behavior microservices architecture\n- Intelligent behavior load balancing\n- Support for both local and distributed behaviors\n- Advanced behavior analytics and monitoring\n- Support for behavior containerization\n- Compliance with automotive behavior standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle behavior design.",
    ],
    "generate_operations": [
        "Design a comprehensive operations sequence focusing on {key}. Requirements:\n\n1. Multiple operation types with different execution characteristics\n2. Proper operation sequencing and dependency management\n3. Support for both sequential and parallel operation execution\n4. Advanced timing and synchronization mechanisms\n5. Operation error handling and recovery\n6. Performance optimization and resource management\n7. Operation monitoring and diagnostics\n8. Support for operation testing and validation\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional operation design patterns.",
        "Create an advanced operations sequence architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical operation composition with clear abstraction levels\n- Support for both synchronous and asynchronous operation execution\n- Advanced operation scheduling and priority management\n- Operation dependency resolution and conflict handling\n- Support for operation adaptation and optimization\n- Comprehensive operation monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for operation verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern operation design principles.",
        "Develop a sophisticated operations sequence for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent operation orchestration\n2. Multi-domain operation integration (safety, security, performance)\n3. Advanced operation optimization and learning\n4. Support for distributed operation execution\n5. Operation-based system adaptation and evolution\n6. Advanced operation testing and simulation capabilities\n7. Support for operation evolution and updates\n8. Compliance with automotive operation standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge operation design.",
        "Design an intelligent operations sequence for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time operation execution\n- Enable AI/ML operation integration\n- Provide advanced operation coordination mechanisms\n- Support adaptive operation patterns\n- Include comprehensive operation safety mechanisms\n- Implement intelligent operation resource management\n- Support both deterministic and probabilistic operations\n- Enable seamless operation evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation operation design.",
        "Create a modular operations sequence architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based operation processing\n- Advanced operation security and isolation\n- Support for operation microservices architecture\n- Intelligent operation load balancing\n- Support for both local and distributed operations\n- Advanced operation analytics and monitoring\n- Support for operation containerization\n- Compliance with automotive operation standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle operation design.",
    ],
    "generate_topology": [
        "Design a comprehensive network topology focusing on {key}. Requirements:\n\n1. Multiple network segments with different characteristics\n2. Proper network routing and switching mechanisms\n3. Support for both wired and wireless communication\n4. Advanced network security and access control\n5. Network performance optimization and QoS management\n6. Fault tolerance and redundancy mechanisms\n7. Network monitoring and diagnostics\n8. Support for network testing and validation\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional network design patterns.",
        "Create an advanced network topology architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical network architecture with clear segmentation\n- Support for both deterministic and best-effort communication\n- Advanced network protocols and standards compliance\n- Network virtualization and software-defined networking\n- Support for network adaptation and optimization\n- Comprehensive network monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for network verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern network design principles.",
        "Develop a sophisticated network topology for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent network orchestration\n2. Multi-domain network integration (safety, security, performance)\n3. Advanced network optimization and learning\n4. Support for distributed network management\n5. Network-based system adaptation and evolution\n6. Advanced network testing and simulation capabilities\n7. Support for network evolution and updates\n8. Compliance with automotive network standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge network design.",
        "Design an intelligent network topology for autonomous vehicles with focus on {key}. The system must:\n\n- Support high-bandwidth sensor data networks\n- Enable real-time communication protocols\n- Provide advanced network security mechanisms\n- Support adaptive network behavior\n- Include comprehensive network safety mechanisms\n- Implement intelligent network resource management\n- Support both deterministic and probabilistic networks\n- Enable seamless network evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation network design.",
        "Create a modular network topology architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based network services\n- Advanced network security and encryption\n- Support for network microservices architecture\n- Intelligent network load balancing\n- Support for both local and distributed networks\n- Advanced network analytics and monitoring\n- Support for network virtualization\n- Compliance with automotive network standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle network design.",
    ],
    "generate_cpu": [
        "Design a comprehensive CPU architecture focusing on {key}. Requirements:\n\n1. Multiple CPU cores with different performance characteristics\n2. Proper core scheduling and load balancing mechanisms\n3. Support for both symmetric and asymmetric multiprocessing\n4. Advanced cache hierarchy and memory management\n5. CPU power management and thermal control\n6. Performance monitoring and optimization\n7. CPU security and access control mechanisms\n8. Support for CPU testing and validation\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional CPU design patterns.",
        "Create an advanced CPU architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical CPU architecture with clear performance tiers\n- Support for both real-time and general-purpose processing\n- Advanced CPU virtualization and containerization\n- CPU-based system optimization and learning\n- Support for CPU adaptation and optimization\n- Comprehensive CPU monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for CPU verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern CPU design principles.",
        "Develop a sophisticated CPU architecture for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for heterogeneous computing architectures\n2. Multi-domain CPU integration (safety, security, performance)\n3. Advanced CPU orchestration and workload management\n4. Support for distributed CPU execution\n5. CPU-based system adaptation and evolution\n6. Advanced CPU testing and simulation capabilities\n7. Support for CPU evolution and updates\n8. Compliance with automotive CPU standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge CPU design.",
        "Design an intelligent CPU architecture for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time AI/ML processing\n- Enable advanced sensor data processing\n- Provide comprehensive CPU security mechanisms\n- Support adaptive CPU behavior\n- Include comprehensive CPU safety mechanisms\n- Implement intelligent CPU resource management\n- Support both deterministic and probabilistic processing\n- Enable seamless CPU evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation CPU design.",
        "Create a modular CPU architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based CPU services\n- Advanced CPU security and isolation\n- Support for CPU microservices architecture\n- Intelligent CPU load balancing\n- Support for both local and distributed processing\n- Advanced CPU analytics and monitoring\n- Support for CPU virtualization\n- Compliance with automotive CPU standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle CPU design.",
    ],
    "generate_generic_hw": [
        "Design a comprehensive generic hardware architecture focusing on {key}. Requirements:\n\n1. Multiple hardware components with different characteristics\n2. Proper hardware abstraction and driver management\n3. Support for both standard and custom hardware interfaces\n4. Advanced hardware resource management and allocation\n5. Hardware power management and thermal control\n6. Performance monitoring and optimization\n7. Hardware security and access control mechanisms\n8. Support for hardware testing and validation\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional hardware design patterns.",
        "Create an advanced generic hardware architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical hardware architecture with clear abstraction levels\n- Support for both real-time and non-real-time hardware access\n- Advanced hardware virtualization and abstraction\n- Hardware-based system optimization and learning\n- Support for hardware adaptation and optimization\n- Comprehensive hardware monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for hardware verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern hardware design principles.",
        "Develop a sophisticated generic hardware architecture for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for heterogeneous hardware architectures\n2. Multi-domain hardware integration (safety, security, performance)\n3. Advanced hardware orchestration and resource management\n4. Support for distributed hardware execution\n5. Hardware-based system adaptation and evolution\n6. Advanced hardware testing and simulation capabilities\n7. Support for hardware evolution and updates\n8. Compliance with automotive hardware standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge hardware design.",
        "Design an intelligent generic hardware architecture for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time sensor data processing\n- Enable advanced AI/ML hardware acceleration\n- Provide comprehensive hardware security mechanisms\n- Support adaptive hardware behavior\n- Include comprehensive hardware safety mechanisms\n- Implement intelligent hardware resource management\n- Support both deterministic and probabilistic hardware\n- Enable seamless hardware evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation hardware design.",
        "Create a modular generic hardware architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based hardware services\n- Advanced hardware security and isolation\n- Support for hardware microservices architecture\n- Intelligent hardware load balancing\n- Support for both local and distributed hardware\n- Advanced hardware analytics and monitoring\n- Support for hardware virtualization\n- Compliance with automotive hardware standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle hardware design.",
    ],
    "generate_power_params": [
        "Design a comprehensive power management system focusing on {key}. Requirements:\n\n1. Multiple power domains with different characteristics\n2. Proper power sequencing and dependency management\n3. Support for both static and dynamic power management\n4. Advanced power monitoring and optimization\n5. Power security and access control mechanisms\n6. Thermal management and cooling strategies\n7. Power testing and validation frameworks\n8. Support for power evolution and updates\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional power management design.",
        "Create an advanced power management architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical power architecture with clear power domains\n- Support for both centralized and distributed power management\n- Advanced power optimization and learning algorithms\n- Power-based system adaptation and optimization\n- Support for power adaptation and optimization\n- Comprehensive power monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for power verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern power management principles.",
        "Develop a sophisticated power management system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent power orchestration\n2. Multi-domain power integration (safety, security, performance)\n3. Advanced power optimization and learning\n4. Support for distributed power management\n5. Power-based system adaptation and evolution\n6. Advanced power testing and simulation capabilities\n7. Support for power evolution and updates\n8. Compliance with automotive power standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge power management design.",
        "Design an intelligent power management system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time power optimization\n- Enable advanced AI/ML power management\n- Provide comprehensive power security mechanisms\n- Support adaptive power behavior\n- Include comprehensive power safety mechanisms\n- Implement intelligent power resource management\n- Support both deterministic and probabilistic power management\n- Enable seamless power evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation power management design.",
        "Create a modular power management architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based power services\n- Advanced power security and isolation\n- Support for power microservices architecture\n- Intelligent power load balancing\n- Support for both local and distributed power management\n- Advanced power analytics and monitoring\n- Support for power virtualization\n- Compliance with automotive power standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle power management design.",
    ],
    "generate_mapping": [
        "Design a comprehensive hardware-software mapping system focusing on {key}. Requirements:\n\n1. Multiple mapping strategies with different characteristics\n2. Proper resource allocation and load balancing\n3. Support for both static and dynamic mapping\n4. Advanced mapping optimization and performance tuning\n5. Mapping security and access control mechanisms\n6. Performance monitoring and diagnostics\n7. Mapping testing and validation frameworks\n8. Support for mapping evolution and updates\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional mapping design.",
        "Create an advanced hardware-software mapping architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical mapping architecture with clear abstraction levels\n- Support for both centralized and distributed mapping\n- Advanced mapping optimization and learning algorithms\n- Mapping-based system adaptation and optimization\n- Support for mapping adaptation and optimization\n- Comprehensive mapping monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for mapping verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern mapping design principles.",
        "Develop a sophisticated hardware-software mapping system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent mapping orchestration\n2. Multi-domain mapping integration (safety, security, performance)\n3. Advanced mapping optimization and learning\n4. Support for distributed mapping management\n5. Mapping-based system adaptation and evolution\n6. Advanced mapping testing and simulation capabilities\n7. Support for mapping evolution and updates\n8. Compliance with automotive mapping standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge mapping design.",
        "Design an intelligent hardware-software mapping system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time mapping optimization\n- Enable advanced AI/ML mapping algorithms\n- Provide comprehensive mapping security mechanisms\n- Support adaptive mapping behavior\n- Include comprehensive mapping safety mechanisms\n- Implement intelligent mapping resource management\n- Support both deterministic and probabilistic mapping\n- Enable seamless mapping evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation mapping design.",
        "Create a modular hardware-software mapping architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based mapping services\n- Advanced mapping security and isolation\n- Support for mapping microservices architecture\n- Intelligent mapping load balancing\n- Support for both local and distributed mapping\n- Advanced mapping analytics and monitoring\n- Support for mapping virtualization\n- Compliance with automotive mapping standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle mapping design.",
    ],
    "generate_pre_built": [
        "Design a comprehensive pre-built application system focusing on {key}. Requirements:\n\n1. Multiple application types with different characteristics\n2. Proper application lifecycle and state management\n3. Support for both embedded and cloud-based applications\n4. Advanced application optimization and performance tuning\n5. Application security and access control mechanisms\n6. Performance monitoring and diagnostics\n7. Application testing and validation frameworks\n8. Support for application evolution and updates\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional application design.",
        "Create an advanced pre-built application architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical application architecture with clear abstraction levels\n- Support for both monolithic and microservice architectures\n- Advanced application optimization and learning algorithms\n- Application-based system adaptation and optimization\n- Support for application adaptation and optimization\n- Comprehensive application monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for application verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern application design principles.",
        "Develop a sophisticated pre-built application system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent application orchestration\n2. Multi-domain application integration (safety, security, performance)\n3. Advanced application optimization and learning\n4. Support for distributed application execution\n5. Application-based system adaptation and evolution\n6. Advanced application testing and simulation capabilities\n7. Support for application evolution and updates\n8. Compliance with automotive application standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge application design.",
        "Design an intelligent pre-built application system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time application processing\n- Enable advanced AI/ML application integration\n- Provide comprehensive application security mechanisms\n- Support adaptive application behavior\n- Include comprehensive application safety mechanisms\n- Implement intelligent application resource management\n- Support both deterministic and probabilistic applications\n- Enable seamless application evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation application design.",
        "Create a modular pre-built application architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based application services\n- Advanced application security and isolation\n- Support for application microservices architecture\n- Intelligent application load balancing\n- Support for both local and distributed applications\n- Advanced application analytics and monitoring\n- Support for application containerization\n- Compliance with automotive application standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle application design.",
    ],
    "generate_chiplet": [
        "Design a comprehensive chiplet configuration system focusing on {key}. Requirements:\n\n1. Multiple chiplet types with different characteristics\n2. Proper chiplet integration and communication protocols\n3. Support for both homogeneous and heterogeneous chiplets\n4. Advanced chiplet optimization and performance tuning\n5. Chiplet security and access control mechanisms\n6. Performance monitoring and diagnostics\n7. Chiplet testing and validation frameworks\n8. Support for chiplet evolution and updates\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional chiplet design.",
        "Create an advanced chiplet configuration architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical chiplet architecture with clear abstraction levels\n- Support for both centralized and distributed chiplet management\n- Advanced chiplet optimization and learning algorithms\n- Chiplet-based system adaptation and optimization\n- Support for chiplet adaptation and optimization\n- Comprehensive chiplet monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for chiplet verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern chiplet design principles.",
        "Develop a sophisticated chiplet configuration system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent chiplet orchestration\n2. Multi-domain chiplet integration (safety, security, performance)\n3. Advanced chiplet optimization and learning\n4. Support for distributed chiplet management\n5. Chiplet-based system adaptation and evolution\n6. Advanced chiplet testing and simulation capabilities\n7. Support for chiplet evolution and updates\n8. Compliance with automotive chiplet standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge chiplet design.",
        "Design an intelligent chiplet configuration system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time chiplet processing\n- Enable advanced AI/ML chiplet integration\n- Provide comprehensive chiplet security mechanisms\n- Support adaptive chiplet behavior\n- Include comprehensive chiplet safety mechanisms\n- Implement intelligent chiplet resource management\n- Support both deterministic and probabilistic chiplets\n- Enable seamless chiplet evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation chiplet design.",
        "Create a modular chiplet configuration architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based chiplet services\n- Advanced chiplet security and isolation\n- Support for chiplet microservices architecture\n- Intelligent chiplet load balancing\n- Support for both local and distributed chiplets\n- Advanced chiplet analytics and monitoring\n- Support for chiplet virtualization\n- Compliance with automotive chiplet standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle chiplet design.",
    ],
    "generate_analysis": [
        "Design a comprehensive analysis configuration system focusing on {key}. Requirements:\n\n1. Multiple analysis types with different characteristics\n2. Proper analysis data collection and processing\n3. Support for both real-time and batch analysis\n4. Advanced analysis optimization and performance tuning\n5. Analysis security and access control mechanisms\n6. Performance monitoring and diagnostics\n7. Analysis testing and validation frameworks\n8. Support for analysis evolution and updates\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional analysis design.",
        "Create an advanced analysis configuration architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical analysis architecture with clear abstraction levels\n- Support for both centralized and distributed analysis\n- Advanced analysis optimization and learning algorithms\n- Analysis-based system adaptation and optimization\n- Support for analysis adaptation and optimization\n- Comprehensive analysis monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for analysis verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern analysis design principles.",
        "Develop a sophisticated analysis configuration system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent analysis orchestration\n2. Multi-domain analysis integration (safety, security, performance)\n3. Advanced analysis optimization and learning\n4. Support for distributed analysis execution\n5. Analysis-based system adaptation and evolution\n6. Advanced analysis testing and simulation capabilities\n7. Support for analysis evolution and updates\n8. Compliance with automotive analysis standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge analysis design.",
        "Design an intelligent analysis configuration system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time analysis processing\n- Enable advanced AI/ML analysis integration\n- Provide comprehensive analysis security mechanisms\n- Support adaptive analysis behavior\n- Include comprehensive analysis safety mechanisms\n- Implement intelligent analysis resource management\n- Support both deterministic and probabilistic analysis\n- Enable seamless analysis evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation analysis design.",
        "Create a modular analysis configuration architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based analysis services\n- Advanced analysis security and isolation\n- Support for analysis microservices architecture\n- Intelligent analysis load balancing\n- Support for both local and distributed analysis\n- Advanced analysis analytics and monitoring\n- Support for analysis virtualization\n- Compliance with automotive analysis standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle analysis design.",
    ],
    "generate_swc_behavior": [
        "Design a comprehensive SWC custom behavior system focusing on {key}. Requirements:\n\n1. Multiple behavior types with different characteristics\n2. Proper behavior composition and orchestration\n3. Support for both deterministic and probabilistic behaviors\n4. Advanced behavior optimization and performance tuning\n5. Behavior security and access control mechanisms\n6. Performance monitoring and diagnostics\n7. Behavior testing and validation frameworks\n8. Support for behavior evolution and updates\n\nGenerate a detailed AUTOSAR AE XML configuration that demonstrates professional behavior design.",
        "Create an advanced SWC custom behavior architecture for automotive applications with emphasis on {key}. The design should include:\n\n- Hierarchical behavior architecture with clear abstraction levels\n- Support for both centralized and distributed behavior execution\n- Advanced behavior optimization and learning algorithms\n- Behavior-based system adaptation and optimization\n- Support for behavior adaptation and optimization\n- Comprehensive behavior monitoring and diagnostics\n- Integration with automotive middleware and frameworks\n- Support for behavior verification and formal methods\n\nPlease provide a complete AUTOSAR AE XML that showcases modern behavior design principles.",
        "Develop a sophisticated SWC custom behavior system for next-generation automotive systems focusing on {key}. Key requirements:\n\n1. Support for intelligent behavior orchestration\n2. Multi-domain behavior integration (safety, security, performance)\n3. Advanced behavior optimization and learning\n4. Support for distributed behavior execution\n5. Behavior-based system adaptation and evolution\n6. Advanced behavior testing and simulation capabilities\n7. Support for behavior evolution and updates\n8. Compliance with automotive behavior standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that demonstrates cutting-edge behavior design.",
        "Design an intelligent SWC custom behavior system for autonomous vehicles with focus on {key}. The system must:\n\n- Support real-time behavior processing\n- Enable advanced AI/ML behavior integration\n- Provide comprehensive behavior security mechanisms\n- Support adaptive behavior patterns\n- Include comprehensive behavior safety mechanisms\n- Implement intelligent behavior resource management\n- Support both deterministic and probabilistic behaviors\n- Enable seamless behavior evolution and updates\n\nPlease create a detailed AUTOSAR AE XML configuration that demonstrates next-generation behavior design.",
        "Create a modular SWC custom behavior architecture for connected vehicles emphasizing {key}. Requirements:\n\n- Support for cloud-based behavior services\n- Advanced behavior security and isolation\n- Support for behavior microservices architecture\n- Intelligent behavior load balancing\n- Support for both local and distributed behaviors\n- Advanced behavior analytics and monitoring\n- Support for behavior virtualization\n- Compliance with automotive behavior standards\n\nGenerate a comprehensive AUTOSAR AE XML configuration that showcases modern connected vehicle behavior design.",
    ],
}

# Large diverse prompt templates for improved training variety
DIVERSE_PROMPTS = {
    "small": {
        "conversational": [
            "Hi! Can you help me create a {key} configuration for an automotive system?",
            "I need a simple {key} setup. Can you generate one?",
            "Quick question - how do I configure {key} for a basic ECU?",
            "Could you make a {key} configuration with standard settings?",
            "I'm learning AUTOSAR - can you show me a basic {key} example?",
        ],
        "technical": [
            "{key} specs: Standard automotive config. Generate XML.",
            "Req: {key} with default params. Output XML structure.",
            "Technical spec: Create {key} configuration meeting AUTOSAR standards.",
            "System requirement: {key} element with typical automotive parameters.",
        ],
        "user_friendly": [
            "What would a typical {key} configuration look like?",
            "How should I structure {key} for an automotive ECU?",
            "Can you show me {key} configuration with best practices?",
            "Please create {key} that follows standard automotive patterns.",
        ],
        "narrative": [
            "I'm working on an ADAS project and need {key} configured.",
            "Building a new ECU design - need {key} component.",
            "For my autonomous vehicle project, I require {key} configuration.",
            "Developing a brake system controller. Need {key} defined.",
        ],
        "direct": [
            "Generate {key} configuration.",
            "Create {key} with standard parameters.",
            "Build {key} XML structure.",
            "Design {key} for automotive ECU.",
            "Produce {key} following AUTOSAR schema.",
        ],
    },
    "medium": {
        "conversational": [
            "I'm designing an automotive system for urban driving scenarios. Could you help me create a {key} configuration? The system needs to handle real-time sensor data with low latency (<{latency_us}us) and should be power-efficient. I'd appreciate a configuration that follows AUTOSAR best practices.",
            "Hey, I need your help with {key} for my project. We're building an ADAS system that processes camera and radar data. Requirements include fast response times and reliable communication between components. Can you generate a configuration that meets these needs?",
            "Working on a vehicle braking system and stuck on {key} configuration. The system must meet ASIL-D safety requirements and handle multiple sensor inputs simultaneously. What would you recommend?",
        ],
        "technical": [
            "Technical Requirements for {key}:\n- Operating context: Urban/highway autonomous driving\n- Latency: <{latency_us}us for critical paths\n- Power budget: <{power_mw}mW per hardware IP\n- Safety: ISO 26262 ASIL-D compliance\n\nGenerate compliant AUTOSAR configuration.",
            "System Specification - {key}:\nPlatform: ARMv9 Cortex-A720 ({cpu_cores} cores)\nMemory: <{ram_mb}MB RAM per ECU\nCommunication: CAN/Ethernet hybrid\nReal-time constraints: <2ms response\n\nProvide complete XML configuration.",
        ],
        "user_friendly": [
            "How would you design {key} for a Level 3 autonomous vehicle? The system needs to process lidar and camera data with minimal latency while maintaining power efficiency. What tradeoffs should I consider?",
            "What's the optimal {key} configuration for a safety-critical braking system? It needs redundancy, fail-safe operation, and must meet ISO 26262 ASIL-D requirements. How would you structure this?",
        ],
        "narrative": [
            "I'm developing a next-generation vehicle architecture focused on {key}. The project involves integrating multiple ECUs for different vehicle domains - powertrain, chassis, and ADAS. Each domain has unique timing and safety requirements. The {key} component is critical for inter-domain communication and must support both real-time and non-real-time data flows.",
            "Our team is building an electric vehicle control system where {key} plays a central role. We're using advanced multi-core processors and need efficient task distribution. The system must handle motor control, battery management, and driver assistance simultaneously while maintaining strict timing guarantees.",
        ],
        "direct": [
            "Generate {key} for autonomous driving:\n- Multi-sensor fusion capability\n- Real-time processing <{latency_us}us\n- ISO 26262 ASIL-D compliant\n- Power-optimized design\n- Supports CAN and Ethernet",
            "Create {key} configuration:\n• Safety-critical application\n• {cpu_cores}-core ARM processor\n• <{power_mw}mW power consumption\n• Deterministic scheduling\n• Complete XML output",
        ],
    },
    "large": {
        "conversational": [
            "I'm working on a comprehensive automotive system design and could really use your expertise on {key}. Let me explain the context: we're developing a Level 4 autonomous driving system that needs to integrate sensor fusion, path planning, and vehicle control in real-time. The {key} component is critical for this architecture. \n\nSpecific requirements include:\n- Support for multiple high-bandwidth sensors (cameras, lidar, radar)\n- Real-time processing with <45us latency for critical safety loops\n- Distributed processing across multiple ECUs and SoCs\n- Power-efficient operation (<90mW per hardware IP block)\n- ISO 26262 ASIL-D compliance for safety functions\n- Ethernet-based communication for high-speed data transfer\n\nCan you design a {key} configuration that addresses these needs while following AUTOSAR best practices?",
        ],
        "technical": [
            "Detailed Technical Specification for {key}:\n\n**System Architecture:**\n- Platform: ARMv9 Cortex-A720 multi-cluster ({cpu_cores} cores per cluster)\n- Memory: {ram_mb}MB RAM per ECU, 4MB heap per component\n- Operating System: Linux (AUTOSAR AP ara::com integration)\n\n**Performance Requirements:**\n- Latency: End-to-end <{latency_us}us for critical paths, <2ms for monitoring\n- Data payload: SRI between 64-512 bytes, control frames <128 bytes\n- Throughput: Support 100+ messages/second per interface\n- CPU utilization: <75% per core at peak load\n\n**Power & Thermal:**\n- Active power: <{power_mw}mW per HWIP, <3W total ECU thermal design\n- Idle leakage: <0.4mW per component\n- DVFS support: 800MHz-1GHz range range\n\n**Safety & Standards:**\n- ISO 26262 ASIL-D for safety-critical functions\n- MISRA-compliant naming, no dynamic runtime allocation\n- Deterministic scheduling with priority-based preemption\n\nGenerate complete AUTOSAR AE XML configuration.",
        ],
        "user_friendly": [
            "I'm facing a complex architecture decision regarding {key} and would value your input. The scenario is this: we're designing a next-gen ADAS system that must handle heterogeneous sensors (camera, lidar, radar, ultrasonic) with vastly different data rates and latency requirements. \n\nKey challenges:\n1. How do we structure {key} to support both high-throughput sensor data and low-latency control signals?\n2. What's the best approach for distributing processing across multiple SoCs while maintaining timing guarantees?\n3. How should we handle fault tolerance and graceful degradation if one ECU fails?\n4. What communication patterns work best for sensor fusion workloads?\n\nCould you design a {key} configuration that addresses these architectural questions?",
        ],
        "narrative": [
            "Let me describe the project context for this {key} configuration request. Our company is developing an advanced autonomous vehicle platform that represents a significant leap in capability. The system architecture spans multiple vehicle domains - each with unique characteristics and requirements.\n\nThe powertrain domain requires precise, deterministic control with extremely low latency. The ADAS domain processes massive amounts of sensor data and runs complex AI models for perception and planning. The chassis domain needs reliable, fault-tolerant control for steering and braking. All of this must work together seamlessly.\n\n{key} is at the heart of this architecture, enabling communication and coordination between domains. We need a design that:\n- Scales from development prototypes to production vehicles\n- Supports both current functionality and future enhancements\n- Meets stringent automotive safety and security requirements\n- Optimizes for both performance and power efficiency\n- Enables thorough testing and validation\n\nPlease create a comprehensive {key} configuration that serves as the foundation for this architecture.",
        ],
        "direct": [
            "Comprehensive {key} design requirements:\n\n**Core Components:**\n- Multiple ECUs: Define 2-3 processing units with distinct roles\n- SoC architecture: Include Chiplet/Generic_Hardware/CPU_Cluster structures\n- Communication: SENDER-RECEIVER-INTERFACE with exactly 1 provider + 1 required port each\n- Behavior: Internal behaviors with runnables, timing events, and data access patterns\n\n**System Parameters:**\n- Timing: Critical path <{latency_us}us, non-critical <2ms, period events {period_ms}ms\n- Data: Payloads 50-500 bytes, control <128 bytes\n- Power: Per-HWIP <{power_mw}mW active, <0.3mW idle, total ECU <3W\n- Scheduling: Fixed-priority, core utilization <70%, P95 execution <180us\n\n**Standards Compliance:**\n- Safety: ISO 26262 ASIL-D for critical functions\n- Coding: MISRA-compliant naming conventions\n- Platform: ARMv9 Cortex-A720, {cpu_cores} cores, ≤{ram_mb}MB RAM\n\nGenerate complete, valid AUTOSAR AE XML.",
        ],
    },
}

# Category-specific contexts
CATEGORY_CONTEXTS = {
    "generate_core": "comprehensive automotive ECU system with interfaces, software components, runnables, and HW-SW mappings",
    "generate_interface": "communication interface",
    "generate_swc": "software component",
    "generate_behavior": "internal behavior with runnables and events",
    "generate_operations": "hardware operations sequence",
    "generate_topology": "network topology",
    "generate_cpu": "CPU cluster configuration",
    "generate_generic_hw": "generic hardware IP",
    "generate_power_params": "power parameters",
    "generate_mapping": "hardware-software mapping",
    "generate_pre_built": "pre-built application",
    "generate_chiplet": "chiplet architecture",
    "generate_analysis": "analysis configuration",
    "generate_swc_behavior": "software component behavior",
    "generate_time_latency": "timing/latency element",
}
